services:
  jagoz-postgres-tests:
    container_name: jagoz-postgres-tests
    image: jagoz-postgres-test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mscx2003
      - POSTGRES_DB=jagoz_db
    ports:
      - 5433:5432

  # jagoz-jvm-1 and jagoz-jvm-2 are used to illustrate scenarios with a fixed number of servers
  # with static and well know names.
  jagoz-jvm-1:
    container_name: jagoz-jvm-1
    hostname: jagoz-jvm-1
    image: jagoz-jvm
    environment:
      PORT: 8081
      DB_URL: "jdbc:postgresql://localhost:5432/jagoz?user=postgres&password=mscx2003"
    ports:
      - 8081:8081

  jagoz-jvm-2:
    container_name: jagoz-jvm-2
    hostname: jagoz-jvm-2
    image: jagoz-jvm
    environment:
      PORT: 8082
      DB_URL: "jdbc:postgresql://localhost:5432/jagoz?user=postgres&password=mscx2003"
    ports:
      - 8082:8082

  # jagoz-jvm-dynamic is used to illustrate scenarios with a dynamic number of servers
  # without static and well know names.
  # We will use docker compose scaling to create multiple instances of this service
  jagoz-jvm-dynamic:
    image: jagoz-jvm
    hostname: jagoz-jvm-dynamic
    environment:
      PORT: 8080
      DB_URL: "jdbc:postgresql://localhost:5432/jagoz?user=postgres&password=mscx2003"

  # The service running the load-balancer
  nginx:
    container_name: jagoz-nginx
    image: jagoz-nginx
    ports:
      - 8080:8080
      - 8088:8088
    depends_on:
      - jagoz-jvm-1
      - jagoz-jvm-2

  # Just a machine running ubuntu, with 'dig' installed so that we can observe the docker compose environment.
  ubuntu:
    container_name: ubuntu
    image: jagoz-ubuntu
    tty: true